name = "toss-worker"
main = "src/index.ts"
compatibility_date = "2024-05-01"

[[kv_namespaces]]
binding = "TOSS_KV"
id = ""

[[d1_databases]]
binding = "TOSS_DB"
database_name = "toss-db"
database_id = ""
